#!/bin/bash

arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x -I/home/valka/Документы/Arduino/libraries/uShell librainductor.cpp -o build/librainductor.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x -I/home/valka/Документы/Arduino/libraries/uShell -I/home/valka/Документы/Arduino/libraries/uShell/utility /home/valka/Документы/Arduino/libraries/uShell/gstring.cpp -o build/uShell/gstring.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x -I/home/valka/Документы/Arduino/libraries/uShell -I/home/valka/Документы/Arduino/libraries/uShell/utility /home/valka/Документы/Arduino/libraries/uShell/uShell.cpp -o build/uShell/uShell.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x -I/home/valka/Документы/Arduino/libraries/uShell -I/home/valka/Документы/Arduino/libraries/uShell/utility /home/valka/Документы/Arduino/libraries/uShell/Console.cpp -o build/uShell/Console.cpp.o 
arm-none-eabi-gcc -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/itoa.c -o build/itoa.c.o 
arm-none-eabi-gcc -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/avr/dtostrf.c -o build/dtostrf.c.o 
arm-none-eabi-gcc -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/cortex_handlers.c -o build/cortex_handlers.c.o 
arm-none-eabi-gcc -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/wiring_digital.c -o build/wiring_digital.c.o 
arm-none-eabi-gcc -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/wiring_analog.c -o build/wiring_analog.c.o 
arm-none-eabi-gcc -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/WInterrupts.c -o build/WInterrupts.c.o 
arm-none-eabi-gcc -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/wiring.c -o build/wiring.c.o 
arm-none-eabi-gcc -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/iar_calls_sam3.c -o build/iar_calls_sam3.c.o 
arm-none-eabi-gcc -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/syscalls_sam3.c -o build/syscalls_sam3.c.o 
arm-none-eabi-gcc -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/hooks.c -o build/hooks.c.o 
arm-none-eabi-gcc -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/wiring_shift.c -o build/wiring_shift.c.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/Reset.cpp -o build/Reset.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/Stream.cpp -o build/Stream.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/UARTClass.cpp -o build/UARTClass.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/Print.cpp -o build/Print.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/WMath.cpp -o build/WMath.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/wiring_pulse.cpp -o build/wiring_pulse.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/USARTClass.cpp -o build/USARTClass.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/WString.cpp -o build/WString.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/USB/CDC.cpp -o build/CDC.cpp.o 
#arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/USB/USBCore.cpp -o build/USBCore.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/USB/HID.cpp -o build/HID.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/IPAddress.cpp -o build/IPAddress.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/abi.cpp -o build/abi.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/RingBuffer.cpp -o build/RingBuffer.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/new.cpp -o build/new.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino/main.cpp -o build/main.cpp.o 
arm-none-eabi-ar rcs build/core.a build/itoa.c.o 
arm-none-eabi-ar rcs build/core.a build/dtostrf.c.o 
arm-none-eabi-ar rcs build/core.a build/cortex_handlers.c.o 
arm-none-eabi-ar rcs build/core.a build/wiring_digital.c.o 
arm-none-eabi-ar rcs build/core.a build/wiring_analog.c.o 
arm-none-eabi-ar rcs build/core.a build/WInterrupts.c.o 
arm-none-eabi-ar rcs build/core.a build/wiring.c.o 
arm-none-eabi-ar rcs build/core.a build/iar_calls_sam3.c.o 
arm-none-eabi-ar rcs build/core.a build/syscalls_sam3.c.o 
arm-none-eabi-ar rcs build/core.a build/hooks.c.o 
arm-none-eabi-ar rcs build/core.a build/wiring_shift.c.o 
arm-none-eabi-ar rcs build/core.a build/Reset.cpp.o 
arm-none-eabi-ar rcs build/core.a build/Stream.cpp.o 
arm-none-eabi-ar rcs build/core.a build/UARTClass.cpp.o 
arm-none-eabi-ar rcs build/core.a build/Print.cpp.o 
arm-none-eabi-ar rcs build/core.a build/WMath.cpp.o 
arm-none-eabi-ar rcs build/core.a build/wiring_pulse.cpp.o 
arm-none-eabi-ar rcs build/core.a build/USARTClass.cpp.o 
arm-none-eabi-ar rcs build/core.a build/WString.cpp.o 
arm-none-eabi-ar rcs build/core.a build/CDC.cpp.o 
#arm-none-eabi-ar rcs build/core.a build/USBCore.cpp.o 
arm-none-eabi-ar rcs build/core.a build/HID.cpp.o 
arm-none-eabi-ar rcs build/core.a build/IPAddress.cpp.o 
arm-none-eabi-ar rcs build/core.a build/abi.cpp.o 
arm-none-eabi-ar rcs build/core.a build/RingBuffer.cpp.o 
arm-none-eabi-ar rcs build/core.a build/new.cpp.o 
arm-none-eabi-ar rcs build/core.a build/main.cpp.o 
arm-none-eabi-g++ -c -g -O0 -w -ffunction-sections -fdata-sections -nostdlib -fno-threadsafe-statics --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -Dprintf=iprintf -mcpu=cortex-m3 -DF_CPU=84000000L -DARDUINO=158 -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -D__SAM3X8E__ -mthumb -DUSB_VID=0x2341 -DUSB_PID=0x003e -DUSBCON -DUSB_MANUFACTURER="Unknown" -DUSB_PRODUCT="Arduino Due" -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/libsam -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/CMSIS/Include/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/system/CMSIS/Device/ATMEL/ -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/cores/arduino -I/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x/variant.cpp -o build/variant.cpp.o 
arm-none-eabi-gcc -O0 -Wl,--gc-sections -mcpu=cortex-m3 -T/home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x/linker_scripts/gcc/flash.ld -Wl,-Map,build/librainductor.cpp.map -o build/librainductor.cpp.elf -Lbuild -mthumb -Wl,--cref -Wl,--check-sections -Wl,--gc-sections -Wl,--entry=Reset_Handler -Wl,--unresolved-symbols=report-all -Wl,--warn-common -Wl,--warn-section-align -Wl,--warn-unresolved-symbols -Wl,--start-group build/syscalls_sam3.c.o build/librainductor.cpp.o build/uShell/gstring.cpp.o build/uShell/uShell.cpp.o build/uShell/Console.cpp.o build/variant.cpp.o /home/valka/.local/arduino-1.5.8/hardware/arduino/sam/variants/arduino_due_x/libsam_sam3x8e_gcc_rel.a build/core.a -Wl,--end-group -lm -gcc 
arm-none-eabi-objcopy -O binary build/librainductor.cpp.elf build/librainductor.cpp.bin
